[package]
name = "maxsimd"
version = "0.1.0-alpha"
edition = "2024"
homepage = "https://github.com/cmd-HMN"
description = "This packages is the simd implementations of max sim function for faster calculation"
license = "MIT"
# readme = "README.md"
keywords = ["maxsimd"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "maxsimd"
path="rust-core/lib.rs"
crate-type = ["cdylib", "rlib"]

[lints]
rust.unsafe_code = "allow"

[dependencies]
pyo3 = "0.29.0"
pulp = "0.22.3"
rayon   = "1.10"
numpy   = "0.29"
raw-cpuid = "11"
pyo3-stub-gen = "0.23.0"
intel-mkl-src = { version = "0.8.1", optional = true, features = ["mkl-static-lp64-seq"] }
libc = {version = "0.2", optional = true}
# [dependencies.intel-mkl-src]
# version = "0.8.1"
# optional = true

[dev-dependencies]
criterion = "0.8.2"
approx = "0.5"
rand = "0.10.2"

[build]
jobs = 4

[[bin]]
name = "stub"
path = "rust-core/_bin/stub.rs"

# Adding explanation to this feature 
# This is responsible for mkl backend for 2 thing in benchmarking and in testing
# only use default it is enough, no need for this feature only added for mainly benchmarking
[features]
default = []
dev = ["intel-mkl-src", "libc"]

[profile.bench]
debug = true

[[bench]]
name = "bench"
harness = false
path = "rust-core/benches/bench.rs"
required-features = ["dev"]

# rust tests
[[test]]
name = "rtest"
path = "rust-core/tests/mod.rs"
