[build-system]
requires = ["maturin>=1.15.0,<2.0"]
build-backend = "maturin"

[project]
name = "bbq"
requires-python = ">=3.8"
license = { text = "MIT" }
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python",
]

dependencies = [
    "pymupdf",
    "watchdog",
    "rich",
    "pillow",
    "pyyaml",
    "fastapi",
    "uvicorn",
    "requests",
    "numpy",
]
dynamic = ["version"]

[project.scripts]
bbq = "bbq.src.main:main"

[project.optional-dependencies]
benchmark = [
  "matplotlib>=3.10.9",
  "jinja2>=3.1.6",
  "datasets>=5.0.1",
  "plotly>=7.0.0",
]
dev = ["pytest>=9.1.1"]

[dependency-groups]
dev = ["pytest>=9.1.1"]
benchmark = [
  "matplotlib>=3.10.9",
  "jinja2>=3.1.6",
  "datasets>=5.0.1",
  "plotly>=7.0.0",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]

[tool.maturin]
module-name = "bbq.maxsimd.maxsimd"
python-source = "."

[tool.pyright]
extraPaths = ["bbq"]
