# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import numpy
import numpy.typing
__all__ = [
    "dot_f32",
]

def dot_f32(a: numpy.typing.NDArray[numpy.float32], b: numpy.typing.NDArray[numpy.float32]) -> builtins.float: ...

