from . import quantization
# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing

__all__ = [
    "maxsim",
    "quantization",
    "__version__",
]

def maxsim(
    q: typing.Any,
    d: typing.Any,
    doc_lengths: typing.Optional[typing.Sequence[builtins.int]] = None,
    q_scale: typing.Optional[typing.Any] = None,
    d_scale: typing.Optional[typing.Any] = None,
    q_len: typing.Optional[builtins.int] = None,
    dim: typing.Optional[builtins.int] = None,
    jobs: builtins.int = 1,
    dtype: typing.Optional[builtins.int] = None,
    **kwargs: typing.Any,
) -> builtins.list[builtins.float]: ...

__version__ = "0.1.2-alpha"
